function dr = ...
    dhyperb(hyperb, ...
    p,dpr,dpa,ponoff, ...
    rbest,x,y);                              % dhyperb computes
vmax=p(1);   km=p(2);                       %  dr(i)/dp(j), i.e.
dr = [ -x./(km+x), vmax*x./((km+x).^2) ];   %  dr/dvmax and dr/dkm.